project:
  type: website
  output-dir: docs
  resources:
    - ./Presentations/*.pdf

website:
  title: "Huan Xu, MD, PhD"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - research.qmd
      - teaching.qmd
      - presentations.qmd
      - blog.qmd

format:
  html:
    theme: materia
    css: styles.css
    toc: true



